# Generated by Django 5.1.7 on 2025-04-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='type',
            field=models.CharField(choices=[('Academic', 'Academic Records'), ('Professional', 'Professional Qualifications')], default='Academic', max_length=20),
        ),
    ]
