# Generated by Django 5.0.7 on 2024-08-05 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_course_report_student'),
        ('student', '0005_remove_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='student.student'),
        ),
    ]
