# Generated by Django 5.0.7 on 2024-08-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_students'),
        ('report', '0004_alter_report_student'),
        ('student', '0007_alter_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='student.student'),
        ),
    ]
