# Generated by Django 5.0.7 on 2024-08-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_students'),
        ('report', '0005_report_created_at_alter_report_course_and_more'),
        ('student', '0007_alter_student_courses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('student', 'course')},
        ),
    ]
