# Generated by Django 5.0.7 on 2025-02-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
