# Generated by Django 5.2 on 2025-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recall_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
