# Generated by Django 5.1.7 on 2025-05-21 14:31

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_created_notification_modified_and_more"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
