# Generated by Django 5.1.7 on 2025-05-21 14:45

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
