# Generated by Django 5.1.7 on 2025-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('birth_certificate', 'Birth Certificate'), ('guarantor_form', 'Guarantor’s Form'), ('degree_certificate', 'Degree Certificate')], default='offer_letter', max_length=50),
        ),
    ]
