# Generated by Django 5.1.7 on 2025-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='recall_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Casual', 'Casual'), ('Maternity', 'Maternity')], default='Annual', max_length=20),
        ),
    ]
