# Generated by Django 5.1.7 on 2025-05-21 14:31

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    LeaveApplication = apps.get_model("leave_applications", "LeaveApplication")
    LeaveApplication.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("leave_applications", "0003_leaveapplication_created_leaveapplication_modified_and_more"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
