# Generated by Django 5.1.7 on 2025-05-23 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0006_alter_leaveapplication_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(default='eb957f63-59d6-4703-b503-e57357221483', on_delete=django.db.models.deletion.CASCADE, related_name='user_leave_applications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
