# Generated by Django 5.1.7 on 2025-05-23 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_applications', '0007_leaveapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='employee',
        ),
    ]
