services:
    web:
        build: .
        command:
            - bash
            - -c
            - |
                python manage.py collectstatic --noinput
                gunicorn employeemanagement.wsgi:application -b 0.0.0.0:8000

        volumes:
            - .:/app
        ports:
            - "8000:8000"

    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static:/app/static
        ports:
            - "80:80"
        depends_on:
            - web
