# Generated by Django 5.1.7 on 2025-05-21 14:31

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    Education = apps.get_model("educations", "Education")
    Education.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0002_education_created_education_modified_and_more"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
