# Generated by Django 5.1.7 on 2025-05-21 14:31

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    Kin = apps.get_model("kins", "Kin")
    Kin.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("kins", "0002_kin_created_kin_modified_alter_kin_id"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
