# Generated by Django 5.1.7 on 2025-04-21 05:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_num2', models.CharField(blank=True, max_length=20, null=True)),
                ('city_of_residence', models.CharField(max_length=100)),
                ('residential_address', models.TextField()),
            ],
        ),
    ]
