# Generated by Django 5.1.7 on 2025-04-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_num2',
            new_name='phone_num2',
        ),
    ]
