# Generated by Django 5.2 on 2025-04-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_num_1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
