# Generated by Django 5.1.7 on 2025-04-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_email_remove_contact_phone_num_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_num_2',
            new_name='phone_num2',
        ),
    ]
