# Generated by Django 5.0.7 on 2024-08-05 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('report', '0002_alter_report_description_alter_report_point'),
        ('student', '0004_remove_student_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
