
# Generated by Django 5.1.7 on 2025-05-21 14:31

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    Guarantor = apps.get_model("guarantors", "Guarantor")
    Guarantor.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("guarantors", "0002_guarantor_created_guarantor_modified_and_more"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
