# Generated by Django 5.1.7 on 2025-05-21 14:52

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options_user_created_user_modified_and_more"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
