# Generated by Django 5.1.7 on 2025-05-23 07:38

import constants.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=constants.enums.RoleChoices.choices, default=constants.enums.RoleChoices['EMPLOYEE'], max_length=20),
        ),
    ]
