# Generated by Django 5.1.7 on 2025-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='role',
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=20),
        ),
    ]
