# Generated by Django 5.2 on 2025-04-13 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='line_management',
        ),
        migrations.AddField(
            model_name='job',
            name='line_management',
            field=models.ManyToManyField(blank=True, null=True, related_name='managed_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
