# Generated by Django 5.1.7 on 2025-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_line_management_job_line_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
