# Generated by Django 5.1.7 on 2025-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
