# Generated by Django 5.0.7 on 2024-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('student', '0005_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='student.student'),
        ),
    ]
