# Generated by Django 5.1.7 on 2025-05-21 14:24

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    Documents = apps.get_model("documents", "Document")
    Documents.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_created_document_modified_alter_document_id"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
