# Generated by Django 5.1.7 on 2025-05-21 14:44

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
