# Generated by Django 5.1.7 on 2025-03-24 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=50)),
                ('total_days', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Casual', 'Casual'), ('Maternity', 'Maternity')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('durations', models.IntegerField()),
                ('resumption_date', models.DateField()),
                ('reason', models.TextField()),
                ('document_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
                ('relief_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
