# Generated by Django 5.1.7 on 2025-04-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0002_leaveapplication_recall_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='is_recalled',
            field=models.BooleanField(default=False),
        ),
    ]
