# Generated by Django 5.1.7 on 2025-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0003_leaveapplication_is_recalled'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='days_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='new_resumption_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
