# Generated by Django 5.2 on 2025-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0004_leaveapplication_days_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='document_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
