# Generated by Django 5.2 on 2025-04-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0005_alter_leaveapplication_document_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='recall_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='recalled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recalls_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
