# Generated by Django 5.1.7 on 2025-05-21 14:31

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    Family = apps.get_model("families", "Family")
    Family.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0002_family_created_family_modified_alter_family_id"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
