# Generated by Django 5.0.7 on 2024-08-02 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('report', '0002_alter_report_description_alter_report_point'),
        ('student', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='student', through='student.Enrollment', to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='report.report'),
        ),
    ]
