# Generated by Django 5.0.7 on 2024-08-05 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
