# Generated by Django 5.0.7 on 2024-08-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, editable=False, max_length=200, null=True),
        ),
    ]
