# Generated by Django 5.0.7 on 2024-08-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
    ]
