# Generated by Django 5.1.7 on 2025-03-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document',
        ),
    ]
