# Generated by Django 5.1.7 on 2025-03-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isCandidate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('candidate', 'Candidate'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
