# Generated by Django 5.1.7 on 2025-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('candidate', 'Candidate'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
