# Generated by Django 5.2 on 2025-04-14 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('contact', '0002_remove_contact_email_remove_contact_phone_num_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='contact.contact'),
        ),
    ]
