# Generated by Django 5.1.7 on 2025-03-28 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_iscandidate_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isCandidate',
        ),
    ]
