# Generated by Django 5.2 on 2025-04-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_contact'),
        ('kin', '0002_remove_kin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='kin.kin'),
        ),
    ]
