# Generated by Django 5.1.7 on 2025-04-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_kin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
