# Generated by Django 5.0.7 on 2024-08-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
