# Generated by Django 5.0.7 on 2025-01-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_introductory_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_limit',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
