# Generated by Django 5.0.7 on 2025-01-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_instructor_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AlterField(
            model_name='course',
            name='is_introductory',
            field=models.BooleanField(default=True),
        ),
    ]
