# Generated by Django 5.0.7 on 2025-01-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_instructors_and_more'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='instructors.instructor'),
        ),
    ]
