# Generated by Django 5.0.7 on 2025-01-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_delete_instructor_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
