# Generated by Django 5.0.7 on 2025-02-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_enrollment_user_course_enrollments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrollment_limit',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
