# Generated by Django 5.0.7 on 2025-02-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_enrollment_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
