# Generated by Django 5.0.7 on 2025-02-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_duration'),
        ('instructors', '0003_instructor_first_name_instructor_user'),
        ('student', '0012_student_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course'], name='courses_enr_course__a70609_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='courses_enr_student_5c0023_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_at'], name='courses_enr_enrolle_4b9ba6_idx'),
        ),
    ]
