# Generated by Django 5.0.7 on 2025-02-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_courses_cou_name_eb4cc3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_name_eb4cc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_is_acti_3c7e41_idx',
        ),
    ]
