# Generated by Django 5.1.7 on 2025-05-21 10:45
from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    BankAccount = apps.get_model("bank_accounts", "BankAccount")
    BankAccount.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0002_bankaccount_created_bankaccount_modified_and_more"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
