# Generated by Django 5.0.7 on 2024-08-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_courses_student_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='report',
        ),
    ]
