# Generated by Django 5.0.7 on 2024-08-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_students'),
        ('student', '0005_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
