# Generated by Django 5.0.7 on 2024-08-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_students'),
        ('student', '0006_student_courses_delete_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student', to='courses.course'),
        ),
    ]
