# Generated by Django 5.0.7 on 2025-02-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_student_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
