# Generated by Django 5.0.7 on 2025-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_enrollment_user_course_enrollments_and_more'),
        ('student', '0010_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student', to='courses.course'),
        ),
    ]
