# Generated by Django 5.0.7 on 2025-02-19 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_courses_cou_name_eb4cc3_idx_and_more'),
        ('student', '0012_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user'], name='student_stu_user_id_34f0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='student_stu_email_3e40fe_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='student_stu_is_acti_0c5a73_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['birthday'], name='student_stu_birthda_07c975_idx'),
        ),
    ]
