# Generated by Django 5.2 on 2025-04-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kin',
            name='user',
        ),
    ]
