# Generated by Django 5.1.7 on 2025-05-21 14:31

from django.db import migrations
from django.utils.timezone import now


def set_created(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    Job.objects.filter(created__isnull=True).update(created=now())


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_job_created_at_remove_job_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(set_created),
    ]
